### ISSUE TITLE
Change accepted but the change should be usefull #958

### ISSUE THREAD

**Issue by ayansiddiqui007** [ayansiddiqui007/IgniteSubs#5]
usefull changes or ideas accepted

**Comment by gracyashhh** [comment]
Seems like there is no styling to the site, I am not sure, if you have forgotten to upload those files if so, do upload and if not, I'd like to work on the CSS part

**Comment by gracyashhh** [comment]
lol..isn't reminding you of the css files considered as an contribution ( idea 💡)

**Comment by ayansiddiqui007** [comment]
> lol..isn't reminding you of the css files considered as an contribution ( idea 💡)

I do mind your own work brother ! he is my friend and we both are working on this project so he is doing the css part so he had submitted it and i have merged okay !
